name: Deploy

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: I hereby accept full responsibility for any consequences arising from this workflow dispatch
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Check confirmation statement
        if: ${{ inputs.confirmation != true }}
        run: |
          echo 'You must accept full responsibility. Exiting'
          exit 1

      - name: Check we’re running on a tag, not a branch
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo 'This workflow must be run on a tag! It won’t work otherwise'
          exit 1

      - name: Get release from tag
        id: get-release
        uses: actions/github-script@v7
        with:
          script: |
            return await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: context.ref.slice(10)
            });

      - name: Get environment from tag
        id: get-env
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const tag = context.ref.slice(10);
            const isProd = /^\d+\.\d+\.\d+$/.test(tag);
            if (isProd) {
              return 'prod';
            }
            return 'dev';

      - run: |
          echo "${{ steps.get-env.outputs.result }}"

          echo ${{ toJson(fromJson(steps.get-release.outputs.result).data.body) }}
