name: Deploy

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: I hereby accept full responsibility for any consequences arising from this workflow dispatch
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Check confirmation statement
        if: ${{ inputs.confirmation != true }}
        run: |
          echo 'You must accept full responsibility. Exiting'
          exit 1

      - name: Check we’re running on a tag, not a branch
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo 'This workflow must be run on a tag! It won’t work otherwise'
          exit 1

      - name: Get environment from tag
        id: get-vars
        run: |
          tag=`echo "${{ github.ref }}" | cut -c 11-`

          if [[ "$tag" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              env=prod
          else
              env=dev
          fi

          echo "tag=$tag" >> "$GITHUB_OUTPUT"
          echo "env=$env" >> "$GITHUB_OUTPUT"

      - name: Get changelog from tag
        id: get-changelog
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const resp = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: "${{ steps.get-vars.outputs.tag }}"
            });
            return resp.data.body;

      - run: |
          echo "${{ steps.get-vars.outputs.env }}"
          echo "${{ steps.get-vars.outputs.tag }}"
          echo "${{ steps.get-changelog.outputs.result }}"
